log_path = 'log_files'
parent_path = '/home/airquality/PycharmProjects/'
output_path = 'output_files'
xml_path = 'xml_files'
xml_sandbox_log_file = 'xml_sandbox_p27.log'
xml_sandbox_log_level = 'INFO'
